# Generated by Django 5.2 on 2025-05-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_playlistsong_playlist_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
    ]
