# Generated by Django 5.2 on 2025-05-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_playlist_songs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='songs',
            new_name='songs_old',
        ),
    ]
