# Generated by Django 5.2 on 2025-05-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_rename_songs_playlist_songs_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='songs_old',
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(through='music.PlaylistSong', to='music.song'),
        ),
    ]
